### ISSUE TITLE
Unavailable on NPM

### ISSUE THREAD

**Issue by ffocsi** [brecons/jquery-validation-unobtrusive-bootstrap#2]
Hi,

It would be great if this was available on NPM.

Thanks

**Comment by EliuTimana** [comment]
+1, bower is dead and it would be amazing if we can use via npm or cdn.

**Comment by brecons** [comment]
It's now available on npm and yarn.

https://www.npmjs.com/package/jquery-validation-unobtrusive-bootstrap
