### ISSUE TITLE
Error with $element and $error not being defined

### ISSUE THREAD

**Issue by webcognoscere** [brecons/jquery-validation-unobtrusive-bootstrap#5]
Hi there,

I picked up an error when pulling the latest version, v2.1.0,  under the options/errorPlacement method:

```javascript
 $.validator.unobtrusive.options = {
            errorClass: defaultOptions.errorClass,
            validClass: defaultOptions.validClass,
            errorElement: 'div',
            errorPlacement: function (error, element) {
                error.addClass('invalid-feedback');

                if ($element.next().is(".input-group-append")) {  // <-- $element is not defined (replace with element)
                    $error.insertAfter($element.next()); // <-- $element & $error are not defined (replace with element)
                } else {
                    $error.insertAfter($element); // <-- $element & $error are not defined (replace with element)
                }
            }
        };
```

^ The issue here is both $element and $error aren't defined. 

I updated them (locally) to reference the local vars [element] and [error] respectively and this seemed to have resolved the issue.

Hope this helps and is updated in the next version.

Thanks again for an awesome add-on brecons
-Miguel

**Comment by Cobster** [comment]
Just hit this same issue, and resolved it the same way.

**Comment by brecons** [comment]
Hi Miguel, thanks for your hint. Can you please create a pull request, so I can merge the fix for this issue?

**Comment by brecons** [comment]
#6 Fixed
